import './app.css';
import Header from '../header/header';
import CharactersList from '../characters-list/characters-list';

let data = [
  {
  id:1,
  title:'Человек-паук',
  description:'Укушенный радиоактивным пауком, старшеклассник Питер Паркер обрел скорость, силу и силу паука. Приняв имя Человек-паук, Питер надеялся начать карьеру, используя свои новые способности. Наученный тому,что с большой силой приходит большая ответственность, Паук поклялся использовать свои силы, чтобы помогать людям.',
  comics:[
  'Spider-Man: 101 Ways to End the Clone Saga (1997) #1',
  '2099 Alpha (2019) #1',
  'A YEAR OF MARVELS TPB (Trade Paperback)',
  'A Year of Marvels: April Infinite Comic (2016) #1',
  'A Year of Marvels: February Infinite Comic (2016) #1',
  'A+X (2012) #4',
  'Absolute Carnage (2019) #1',
  'Absolute Carnage (2019) #2',
  'Absolute Carnage (2019) #5',
  'Absolute Carnage: Symbiote Spider-Man (2019) #1',
  'Actor Presents Spider-Man and the Incredible Hulk (2003) #1',
  'Adventures of Spider-Man (1996) #1',
  'Adventures of Spider-Man (1996) #2',
  'Adventures of Spider-Man (1996) #3',
  'Adventures of Spider-Man (1996) #4',
  'Adventures of Spider-Man (1996) #5',
  'Adventures of Spider-Man (1996) #6',
  'Adventures of Spider-Man (1996) #7',
  'Adventures of Spider-Man (1996) #8',
  'Adventures of Spider-Man (1996) #9',
], 
imageName:'Spiderman',
},

{
  id:2,
  title:'Россомаха',
  description:'Рожденный со сверхчеловеческими чувствами и способностью исцелять практически от любой раны, Росомаха был захвачен тайной канадской организацией и получил нерушимый скелет и когти. С ним обращались как с животным, и ему потребовались годы, чтобы взять себя в руки. Теперь он является премьером как "Людей Икс", так и "Мстителей".',
  comics:[
    '5 Ronin (Hardcover)',
    '5 Ronin (2010) #1',
    '5 Ronin (2010) #1',
    'A+X (2012) #1',
    'A+X (2012) #4',
    'A+X (2012) #6',
    'A+X (2012) #9',
    'Acts Of Evil (Trade Paperback)',
    'ACTS OF VENGEANCE CROSSOVERS OMNIBUS (Hardcover)',
    'ACTS OF VENGEANCE CROSSOVERS OMNIBUS (DM Only)(Hardcover)',
    'Age of X: Alpha (2010) #1',
    'Agents of Atlas (2009) #3 (Wolverine Art Appreciation Variant)',
    'Agents of Atlas (2009) #5',
    'Agents of Atlas (2009) #5 (MCGUINNESS VARIANT)',
    'Agents of Atlas: The Complete Collection Vol. 1 (Trade Paperback)',
    'All-New Wolverine Vol. 5: Orphans of X (Trade Paperback)',
    'All-New X-Men (2012) #2',
    'Alpha Flight (1983) #3',
    'Alpha Flight (2011) #7',
    'Alpha Flight (1983) #13',
  ],
  imageName:'rossomaha',
},

{
  id:3,
  title:'Железный человек',
  description:'Раненый, захваченный в плен и вынужденный создавать оружие своими врагами, миллиардер-промышленник Тони Старк вместо этого создал усовершенствованный доспех, чтобы спасти свою жизнь и сбежать из плена. Теперь, с новым взглядом на жизнь, Тони использует свои деньги и интеллект, чтобы сделать мир более безопасным и лучшим местом в качестве Железного Человека.',
  comics:[
    'A+X (2012) #2',
    'A+X (2012) #7',
    'Adam: Legend of the Blue Marvel (2008) #1',
    'Adam: Legend of the Blue Marvel (2008) #2',
    'Adam: Legend of the Blue Marvel (2008) #5',
    'Aero (2019) #11',
    'Aero (2019) #12',
    'Age of Heroes (2010) #1',
    'Age of Heroes (2010) #2',
    'Age of Heroes (2010) #3',
    'Age of Heroes (2010) #4',
    'Age of Innocence: The Rebirth of Iron Man (1996) #1',
    'Age of X: Universe (2011) #1',
    'Age of X: Universe (2011) #2',
    'All-New Iron Manual (2008) #1',
    'All-New, All-Different Avengers (2015) #10',
    'All-New, All-Different Avengers (2015) #11',
    'Alpha Flight (1983) 113',
    'Alpha Flight (1983) 127',
    'The Amazing Spider-Man (2015) #13',
  ],
  imageName:'ironman',
},


{
  id:4,
  title:'Капитан Америка',
  description:'Поклявшись служить своей стране во что бы то ни стало, молодой Стив Роджерс принял сыворотку суперсолдата, чтобы стать американской армией из одного человека. Сражаясь за красно-бело-синих на протяжении более 60 лет, Капитан Америка является живым, дышащим символом свободы и свободы.',
  comics:[
    '',
    '',
    '',
    '',
  ],
  imageName:'captainAmerica',
},


{
  id:5,
  title:'Тор',
  description:'Будучи скандинавским богом грома и молнии, Тор владеет одним из величайших видов оружия, когда-либо созданных, - заколдованным молотом Мьельниром. В то время как другие описывали Тора как чрезмерно мускулистого, туповатого идиота, он довольно умен и сострадательен. Он уверен в себе и никогда, никогда не перестанет бороться за достойное дело.',
  comics:[
    'A+X (2012) #7',
    'Age of Heroes (2010) #1',
    'Age of Heroes (2010) #2',
    'Age of Heroes (2010) #3',
    'Age of Heroes (2010) #4',
    'Alpha: Big Time (2013) #4',
    'Alpha Flight (1983) #1',
    'Alpha Flight (1983) #61',
    'Alpha Flight (1983) #27',
    'The Amazing Spider-Man (1963) #339',
    'Amazing Spider-Man (1999)#500',
    'Amazing Spider-Man (1999)#538',
    'Amazing Spider-Man Annual (1964) #3',
    'Amazing Spider-Man Annual (1964) #16',
    'Amazing Spider-Man Vol. 6 (Trade Paperback)',
    'Art of Marvel Studios TPB Slipcase (Hardcover)',
    'Astonishing Thor (2010) #1',
    'Astonishing Thor (2010) #1 (FOILOGRAM VARIANT)',
    'Astonishing Thor (2010) #2',
    'Astonishing Thor (2010) #3',
  ],
  imageName:'Tor',
},

{
  id:6,
  title:'Халк',
  description:'Попав во время взрыва гамма-бомбы, пытаясь спасти жизнь подростка, доктор Брюс Баннер превратился в невероятно мощное существо по имени Халк. Слишком часто неправильно понимаемый герой, чем злее становится Халк, тем сильнее становится Халк.',
  comics:[
    '5 Ronin (Hardcover)',
    '5 Ronin (2010) #2',
    '5 Ronin (2010) #2 (BROOKS COVER)',
    'A+X (2012) #1',
    'A+X (2012) #7',
    'Absolute Carnage: Immortal Hulk (2019) #1',
    'Actor Presents Spider-Man and the Incredible Hulk (2003) #1',
    'Age of X: Universe (2011) #1',
    'Age of X: Universe (2011) #2',
    'All-New Savage She-Hulk (2009) #1',
    'All-New Savage She-Hulk (2009) #2',
    'Alpha Flight (1983) #29',
    'Alpha Flight (1983) #110',
    'Alpha Flight (1983) #111',
    'Alpha Flight (1983) #127',
    'The Amazing Spider-Man (1963) #14',
    'Amazing Spider-Man (1999) #667',
    'Amazing Spider-Man Annual (1964) #3',
    'Amazing Spider-Man Annual (1964) #12',
    'Amazing Spider-Man Annual (2011) #38',
  ],
  imageName:'halk',
},


{
  id:7,
  title:'Дэдпул',
  description:'Уэйд Уилсон — наёмник. Будучи побочным продуктом программы вооружённых сил под названием «Оружие X», Уилсон приобрёл невероятную силу, проворство и способность к исцелению. Но страшной ценой: его клеточная структура постоянно меняется, а здравомыслие сомнительно. Всё, чего хочет Уилсон, — держаться на плаву в социальной выгребной яме. Но течение в ней слишком быстрое.',
  comics:[
    '5 Ronin (Hardcover)',
    '5 Ronin (2010) #5',
    '5 Ronin (2010) #5 (MCGUINNESS COVER)',
    'A+X (2012) #8',
    'Absolute Carnage Vs. Deadpool (2019) #1',
    'Absolute Carnage Vs. Deadpool (2019) #2',
    'Absolute Carnage Vs. Deadpool (2019) #3',
    'Agent X (2002) #13',
    'Agent X (2002) #14',
    'Agent X (2002) #15',
    'All-New Wolverine (2015) #31',
    'Amazing Spider-Man (1999) #611',
    'Amazing Spider-Man (1999) #620 (DEADPOOL VARIANT)',
    'Amazing Spider-Man Annual (2011) #38',
    'Avengers (2016) #10',
    'Avengers: The Initiative (2007) #33 (DEADPOOL VARIANT)',
    'Avenging Spider-Man (2011) #12',
    'Avenging Spider-Man (2011) #13',
    'Avenging Spider-Man: The Complete Collection (Trade Paperback)',
    'Baby\'s First Deadpool Book (1998) #1',

  ],
  imageName:'Deadpool',
},


{
  id:8,
  title:'Сорвиголова',
  description:'Брошенный матерью, Мэтт Мердок был воспитан своим отцом, боксером "Сражающимся Джеком" Мердоком, в Адской кухне. Понимая, что правила необходимы для того, чтобы люди не вели себя плохо, молодой Мэтт решил изучать право; однако, когда он спас человека от встречного грузовика, он разлил радиоактивный груз, который сделал Мэтта слепым, одновременно усиливая его оставшиеся чувства. Под суровой опекой слепого мастера боевых искусств Стика Мэтт овладел своими обостренными чувствами и стал грозным бойцом.',
  comics:[
    'ACTS OF VENGEANCE CROSSOVERS OMNIBUS (Hardcover)',
    'ACTS OF VENGEANCE CROSSOVERS OMNIBUS (DM Only) (Hardcover)',
    'Alias (2001) #10',
    'Alias Omnibus (Hardcover)',
    'Alpha Flight (1983) #1',
    'Alpha Flight (1983) #127',
    'Amazing Spider-Man (1999) #1',
    'The Amazing Spider-Man (1963) #16',
    'The Amazing Spider-Man (1963) #396',
    'Amazing Spider-Man (1999) #538',
    'Amazing Spider-Man (1999) #566',
    'Amazing Spider-Man (1999) #567',
    'Amazing Spider-Man (1999) #587',
    'Amazing Spider-Man (1999) #600',
    'Amazing Spider-Man (1999) #600 (2ND PRINTING VARIANT)',
    'Amazing Spider-Man (1999) #677',
    'Amazing Spider-Man Annual (1964) #3',
    'Amazing Spider-Man Annual (1964) #15',
    'Amazing Spider-Man: Extra! (2008) #1',
    'Astonishing Tales (2009) #4',
  ],
  imageName:'daredavil',
},

{
  id:9,
  title:'Каратель',
  description:'ветеран войны, прошедший боевую подготовку в самых элитных спецподразделениях. Он владеет всеми видами огнестрельного оружия.',
  comics:[
    '5 Ronin (Hardcover)',
    '5 Ronin (2010) #3',
    'A Year of Marvels: November Infinite Comic (2016) #1',
    'A Year of Marvels: The Uncanny (2016) #1',
    'Adventures of Spider-Man (1996) #1',
    'Agent X (2002) #2',
    'Amazing Spider-Man (1999) #537',
    'Amazing Spider-Man (1999) #577',
    'Amazing Spider-Man (1999) #655',
    'Amazing Spider-Man (1999) #655 (2nd Printing Variant)',
    'Amazing Spider-Man Annual (1964) #15',
    'Astonishing Tales (2009) #1',
    'Astonishing Tales (2009) #2',
    'Astonishing Tales (2009) #3',
    'Astonishing Tales (2009) #4',
    'Astonishing Tales (2009) #5',
    'Avengers Assemble Vol. 4 (Hardcover)',
    'Avenging Spider-Man (2011) #6',
    'Avenging Spider-Man (2011) #22',
    'Black Widow (2014) #1',
],
  imageName:'punisher',
},

{
  id:10,
  title:'Доктор Стрэндж',
  description:'Страшная автокатастрофа поставила крест на карьере успешного нейрохирурга Доктора Стрэнджа. Отчаявшись, он отправляется в путешествие в поисках исцеления и открывает в себе невероятные способности к трансформации пространства и времени. Теперь он - связующее звено между параллельными измерениями, а его миссия - защищать жителей Земли и противодействовать Злу, какое бы обличие оно ни принимало.',
  comics:[
    'A+X (2012) #9',
    'ACTS OF VENGEANCE CROSSOVERS OMNIBUS (Hardcover)',
    'ACTS OF VENGEANCE CROSSOVERS OMNIBUS (DM Only)(Hardcover)',
    'All-New Guardians of the Galaxy (2017) #12',
    'All-New Wolverine (2015) #4',
    'Alpha Flight (1983) #127',
    'The Amazing Spider-Man (1963) #336',
    'Amazing Spider-Man (1999) #500',
    'Amazing Spider-Man (1999) #504',
    'Amazing Spider-Man (1999) #639',
    'Amazing Spider-Man (1999) #640',
    'Amazing Spider-Man (1999) #673',
    'Amazing Spider-Man Annual (1964) #1',
    'Amazing Spider-Man Annual (1964) #2',
    'Amazing Spider-Man Annual (1964) #14',
    'Amazing Spider-Man Vol. 6 (Trade Paperback)',
    'AMAZING SPIDER-MAN VOL. 7: BOOK OF EZEKIEL TPB (Trade Paperback)',
    'Amazing Spider-Man Vol. 7: The Book of Ezekiel (Trade Paperback)',
    'Avengers (2018) #1',
    'Avengers (2018) #2',
  ],
  imageName:'doctorStrange',
},

{
  id:11,
  title:'Черная Пантера',
  description:'С первого взгляда можно решить, что Ваканда - обычная территория дикой Африки, но это не так. Здесь, в недрах пустынных земель, скрываются залежи уникального металла, способного поглощать вибрацию. Многие пытались добраться до него, разоряя всё на своём пути и принося смерть аборигенам, но каждый раз таинственный дух саванны - Чёрная Пантера - вставал на защиту угнетённых. Спустя много лет беда снова приходит в Ваканду, и в этот раз враг заручился поддержкой современных технологий. Когда шансов почти не остаётся, Т\'Чалла, молодой принц Ваканды, узнаёт, что именно ему предстоит возродить легенду и продолжить вечную борьбу, надев маску Чёрной Пантеры',
  comics:[
    'A+X (2012) #3',
    'AGE OF HEROES TPB (Trade Paperback)',
    'Amazing Spider-Man Annual (1964) #15',
    'Amazing Spider-Man Annual (1964) #25',
    'Astonishing Tales (1970) #6',
    'Astonishing X-Men (2004) #51 (Create Your Own Wedding Variant)',
    'Avengers (2018) #1',
    'Avengers (1998) #1',
    'Avengers (2018) #2',
    'Avengers (1998) #2',
    'Avengers (1998) #3',
    'Avengers (1998) #4',
    'Avengers (2018) #6',
    'Avengers (2018) #12',
    'Avengers (1998) #19',
    'Avengers (1998) #20',
    'Avengers (1998) #21',
    'Avengers (1998) #22',
    'Avengers (1998) #23',
    'Avengers (2018) #36',
  ],
  imageName:'DarkPantera',
},

{
  id:12,
  title:'Оса',
  description:'Когда умер отец Джанет Ван Дайн, она убедила партнера своего отца Хэнка Пима дать ей запас "частиц Пима"; Пим также подверг ее процедуре, которая дала ей возможность, уменьшившись, вырастить крылья и выстрелить взрывами энергии, которые она назвала "укусами осы".',
  comics:[
    'Adam: Legend of the Blue Marvel (2008) #1',
    'All-New Wolverine (2015) #5',
    'All-New, All-Different Avengers (2015) #14',
    'Ant-Man & the Wasp: Living Legends (2018) #1',
    'Ant-Man and the Wasp Adventures (Digest)',
    'Ant-Man: Astonishing Origins (Trade Paperback)',
    'Avengers (1998) #1',
    'Avengers (1998) #2',
    'Avengers (1996) #3',
    'Avengers (1998) #3',
    'Avengers (1996) #4',
    'Avengers (1998) #4',
    'Avengers (1963) #5',
    'Avengers (1963) #8',
    'Avengers (1996) #9',
    'Avengers (1998) #10',
    'Avengers (1963) #10',
    'Avengers (1996) #10',
    'Avengers (1996) #11',
    'Avengers (1998) #11',
],
  imageName:'Osa',
},

{
  id:13,
  title:'Блэйд',
  description:'Мужчина, который позже станет известен как "Блэйд" родился в борделе Сохо, Великобритания в 1929 году. Его отец, Лукас Кросс (Lucas Cross), член тайного общества "Орден Тираны" (Order of Tyrana) (прим. - организация, специализирующаяся на вопросах оккультизма, особенно вампиризма), отправил свою беременную жену Тару (Tara) в Англию, прежде чем был пленён в Латверии (Latveria). Там она и находит свой второй дом, поселившись у владелицы борделя Мадам Ванити (Madame Vanity), другого члена "Ордена Тирана", под именем Ванессы Брукс (Vanessa Brooks). ​',
  comics:[
    'Avengers (2018) #16',
    'Avengers (2018) #45',
    'Black Panther (2005) #12',
    'Black Panther by Reginald Hudlin: The Complete Collection Vol. 1 (Trade Paperback)',
    'Black Panther: Bad Mutha (Trade Paperback)',
    'Blade (1998) #1',
    'Blade (2006) #1',
    'Blade (2006) #2',
    'Blade (1998) #2',
    'Blade (2006) #3',
    'Blade (1998) #3',
    'Blade (2006) #4',
    'Blade (2006) #5',
    'Blade (2006) #5 (Bloody Variant)',
    'Blade (2006) #6',
    'Blade (2006) #7',
    'Blade (2006) #8',
    'Blade (2006) #9',
    'Blade (2006) #10',
    'Blade (2006) #11',
],
  imageName:'Blade',
},

{
  id:14,
  title:'Черная вдова',
  description:'Наташе Романофф предстоит лицом к лицу встретиться со своим прошлым. Чёрной Вдове придется вспомнить о том, что было в её жизни задолго до присоединения к команде Мстителей, и узнать об опасном заговоре, в который оказываются втянуты её старые знакомые — Елена, Алексей (известный как Красный Страж) и Мелина.',
  comics:[
    'A+X (2012) #2',
    'A+X (2012) #10',
    'Adam: Legend of the Blue Marvel (2008) #1',
    'Amazing Adventures (1970) #1',
    'Amazing Adventures (1970) #2',
    'Amazing Adventures (1970) #3',
    'Amazing Adventures (1970) #4',
    'Amazing Adventures (1970) #5',
    'Amazing Adventures (1970) #6',
    'Amazing Adventures (1970) #7',
    'Amazing Adventures (1970) #8',
    'Amazing Spider-Man (1999) #684',
    'Amazing Spider-Man (1999) #685',
    'Amazing Spider-Man (1999) #686',
    'Amazing Spider-Man (1999) #687',
    'Avengers (1998) #1',
    'Avengers (1998) #2',
    'Avengers (1998) #3',
    'Avengers (1998) #4',
    'Avengers (1998) #27',
],
  imageName:'blackWidow',
},

{
  id:15,
  title:'Соколиный Глаз',
  description:'Бартон с четырнадцати лет путешествовал с бродячим цирком, где его природную меткость заметили звезды шоу Фехтовальщик и Трикшот. Они помогли юному Бартону освоить акробатику, стрельбу из лука и научили метать ножи. Когда Бартон выяснил, что оба его наставника — преступники, он покинул цирк и долгое время выступал на ярмарках и карнавалах под псевдонимом Соколиный Глаз.',
  comics:[
    'A+X (2012) #3',
    'A+X (2012) #8',
    'All-New Hawkeye (2015) #1',
    'All-New Hawkeye (2015) #2',
    'All-New Hawkeye (2015) #3',
    'All-New Hawkeye (2015) #4',
    'All-New Hawkeye (2015) #5',
    'Amazing Spider-Man (1999) #666',
    'Amazing Spider-Man (1999) #667',
    'Amazing Spider-Man (1999) #668',
    'Amazing Spider-Man (1999) #670',
    'Annihilators: Earthfall (2011) #2',
    'Ant-Man and the Wasp Adventures (Digest)',
    'Avengers (2010) #1',
    'Avengers (2010) #1 (DJURDJEVIC VARIANT)',
    'Avengers (2010) #1 (ROMITA SR. VARIANT)',
    'Avengers (2010) #1 (I AM AN AVENGER BLANK COVER VARIANT)',
    'Avengers (2010) #1 (HEROIC AGE VARIANT)',
    'Avengers (2010) #1 (ROMITA JR. VARIANT)',
    'Avengers (2010) #2',
],
  imageName:'Hawkeye',
},

{
  id:16,
  title:'Фантастическая четверка',
  description:'После воздействия космических лучей Рид Ричардс, Сьюзен Сторм, Бен Гримм и Джонни Сторм обнаружили, что у них появились удивительные новые способности. Рид Ричардс обнаружил, что у него есть способность растягивать свое тело так, как он хочет, в то время как Сьюзен Сторм может сделать себя, предметы и других людей невидимыми. Бен Гримм превратился в скалистого, сверхсильного бегемота, а Джонни Шторм обладает способностью поджигать себя. Получившие название "Фантастическая четверка", "Мистер Фантастика", "Невидимая женщина", "Вещь" и "Человеческий факел" - первая семья Marvel.',
  comics:[
    '4 (2004) #1',
    '4 (2004) #2',
    '4 (2004) #3',
    '4 (2004) #4',
    '4 (2004) #5',
    '4 (2004) #6',
    '4 (2004) #7',
    '4 (2004) #8',
    '4 (2004) #9',
    '4 (2004) #10',
    '4 (2004) #11',
    '4 (2004) #12',
    '4 (2004) #13',
    '4 (2004) #14',
    '4 (2004) #15',
    '4 (2004) #16',
    '4 (2004) #17',
    '4 (2004) #18',
    '4 (2004) #19',
    '4 (2004) #20',
],
  imageName:'fantastic4',
},

{
  id:17,
  title:'Люк Кейдж',
  description:'В какой-то момент Кейдж участвовал в эксперименте, и его кожа стала настолько прочной, что ее невозможно было повредить чем-либо. Люк был женат на Реве Коннорс, которая, как считалось, погибла в результате аварии на дороге (была сбита автобусом). («AKA Это называется виски») Однако Кейдж почувствовал, что в этом происшествии было что-то не так, и от него скрывают существенную информацию, а потому посвятил свою жизнь поискам того, кто действительно был виновен в смерти его жены.',
  comics:[
    'Age of Ultron (2013) #3',
    'Age of Ultron (2013) #4',
    'Alias (2001) #1',
    'Alias (2001) #2',
    'Alias (2001) #3',
    'Alias (2001) #15',
    'Alias Omnibus (Hardcover)',
    'Amazing Spider-Man (1999) #519',
    'Amazing Spider-Man (1999) #520',
    'Amazing Spider-Man (1999) #522',
    'Amazing Spider-Man (1999) #523',
    'Amazing Spider-Man (1999) #601',
    'Amazing Spider-Man (1999) #653',
    'Amazing Spider-Man (1999) #654',
    'Amazing Spider-Man (1999) #654 (2nd Printing Variant)',
    'Amazing Spider-Man (1999) #666',
    'Amazing Spider-Man (1999) #667',
    'Amazing Spider-Man (1999) #669 (Slott Variant)',
    'Amazing Spider-Man (1999) #669 (Architect Variant)',
    'Amazing Spider-Man Annual (2012) #39',
],
  imageName:'LukуСeyge',
},

{
  id:18,
  title:'Железный кулак',
  description:'Дэниел Рэнд - сын бизнесмена Венделла Рэнда, который когда-то жил в загадочном городе К\'унь-Луне, что располагается в другом измерении. Известный там как Венделл Рэнд-К\'аи он был наследником и старшим сыном тамошнего правителя Лорда Туана, который усыновил Рэнда в благодарность за спасение своей жизни.',
  comics:[
    'Pulse (2004) #6',
],
  imageName:'IronFist',
},

{
  id:19,
  title:'Джессика Джонс',
  description:'Джессика родилась в семье Брайана и Алисии Джонс. У Джессики был младший брат по имени Филипп. Во время одной из семейных поездок, у Джонс произошла ссора с младшим братом. Брайан отвлекся, и машина попала в аварию. Джессика впала в кому, а вся остальная семья погибла.',
  comics:[
    'Alias (2001) #1',
    'Alias (2001) #2',
    'Alias (2001) #3',
    'Alias (2001) #4',
    'Alias (2001) #5',
    'Alias (2001) #6',
    'Alias (2001) #7',
    'Alias (2001) #8',
    'Alias (2001) #9',
    'Alias (2001) #10',
    'Alias (2001) #11',
    'Alias (2001) #12',
    'Alias (2001) #13',
    'Alias (2001) #14',
    'Alias (2001) #15',
    'Alias (2001) #16',
    'Alias (2001) #17',
    'Alias (2001) #18',
    'Alias Omnibus (Hardcover)',
    'Amazing Spider-Man (1999) #601',
],
  imageName:'JessicaJones',
}

]

function App() {
  return (
    <div className="App">
      <Header/>
      <CharactersList data={data}/>
    </div>
  );
}

export default App;
